### ISSUE TITLE
Predefined options

### ISSUE THREAD

**Issue by Szmyk** [Szmyk/gmbt#12]
Possibility to set predefined console arguments in config file:

```yaml
options:
  - "world": "-world=WORLD.ZEN"
  - "anotherworld": "--windowed --world=WORLD2.ZEN"
```

and then using them eg. like this: `gmbt test anotherworld`.
