### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by Szmyk** [Szmyk/gmbt#4]
# Hooks 

Hooks system will be very similar to `git` functionality of specifying scripts that git will call based on different events and actions.

Hooks will be defined in YAML config, eg. something like this:

```yaml

hooks:
  - 'common-pre': 'scripts\pre.bat'
  - 'common-pre-subtitles-convert': 'scripts\pre-subtitles-convert.bat'
  - 'test-pre-subtitles-convert': 'scripts\pre-subtitles-convert-test.bat'
  - 'quickTest-pre-subtitles-convert': 'scripts\pre-subtitles-convert-quick-test.bat'
  - 'fullTest-pre-textures-compile': 'scripts\pre-textures-compile.bat'
  - 'build-pre-game-start': 'scripts\pre-game-start.bat'

 etc...
```

# Proposals of hooks

## Common 
- `pre`
- `post`
- `pre-assets-merge`
- `pre-subtitles-convert`
- `pre-textures-compile`
- `pre-game-start`

## Build
- `pre-vdf-build`
- `post-vdf-build`
